# Generated by Django 3.1.2 on 2020-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0004_auto_20201120_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prop', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
