# Generated by Django 3.1.5 on 2021-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0005_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commune',
            name='year',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='year',
        ),
        migrations.RemoveField(
            model_name='epci',
            name='year',
        ),
        migrations.RemoveField(
            model_name='region',
            name='year',
        ),
        migrations.AddField(
            model_name='departement',
            name='category',
            field=models.CharField(choices=[('DEPT', 'Département'), ('PARIS', 'Paris'), ('ML', 'Métropole de Lyon')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='category',
            field=models.CharField(choices=[('REG', 'Région'), ('CTU', 'Collectivité territoriale unique')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear'),
        ),
        migrations.AddField(
            model_name='departement',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear'),
        ),
        migrations.AddField(
            model_name='epci',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear'),
        ),
        migrations.AddField(
            model_name='region',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear'),
        ),
    ]
