# Generated by Django 3.1.5 on 2021-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0006_auto_20210114_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epci',
            name='epci_type',
            field=models.CharField(choices=[('CA', 'Communauté d’agglomération'), ('CC', 'Communauté de communes'), ('CU', 'Communauté urbaine'), ('MET69', 'Métropole de Lyon'), ('METRO', 'Métropole')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='EpciType',
        ),
    ]
