# Generated by Django 3.2 on 2021-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0008_remove_epci_insee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'commune'},
        ),
        migrations.AlterModelOptions(
            name='datayear',
            options={'verbose_name': 'millésime'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name': 'département'},
        ),
        migrations.AlterModelOptions(
            name='epci',
            options={'verbose_name': 'EPCI'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'métadonnée'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'région'},
        ),
        migrations.AddField(
            model_name='commune',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='departement',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='epci',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
