# Generated by Django 3.2.4 on 2021-06-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0011_auto_20210603_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.departement', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='epci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.epci', verbose_name='EPCI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='insee',
            field=models.CharField(max_length=5, verbose_name='identifiant Insee'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='siren',
            field=models.CharField(max_length=9, verbose_name='numéro Siren'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear', verbose_name='millésimes'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='category',
            field=models.CharField(choices=[('DEPT', 'Département'), ('PARIS', 'Paris'), ('ML', 'Métropole de Lyon')], max_length=5, null=True, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='insee',
            field=models.CharField(max_length=3, verbose_name='identifiant Insee'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.region', verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='siren',
            field=models.CharField(max_length=9, verbose_name='numéro Siren'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear', verbose_name='millésimes'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='epci_type',
            field=models.CharField(choices=[('CA', 'Communauté d’agglomération'), ('CC', 'Communauté de communes'), ('CU', 'Communauté urbaine'), ('MET69', 'Métropole de Lyon'), ('METRO', 'Métropole')], max_length=5, null=True, verbose_name='type d’EPCI'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='siren',
            field=models.CharField(max_length=9, verbose_name='numéro Siren'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear', verbose_name='millésimes'),
        ),
        migrations.AlterField(
            model_name='region',
            name='category',
            field=models.CharField(choices=[('REG', 'Région'), ('CTU', 'Collectivité territoriale unique')], max_length=3, null=True, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='region',
            name='insee',
            field=models.CharField(max_length=2, verbose_name='identifiant Insee'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='region',
            name='siren',
            field=models.CharField(max_length=9, verbose_name='numéro Siren'),
        ),
        migrations.AlterField(
            model_name='region',
            name='years',
            field=models.ManyToManyField(to='francesubdivisions.DataYear', verbose_name='millésimes'),
        ),
    ]
