# Generated by Django 3.2.4 on 2021-06-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0012_auto_20210607_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
