# Generated by Django 3.2.4 on 2021-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0013_delete_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='francesubdivisions.datayear', verbose_name='millésime')),
            ],
            options={
                'verbose_name': 'source',
            },
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datacode', models.CharField(max_length=255, verbose_name='valeur')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='valeur')),
                ('datatype', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.region', verbose_name='région')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datasource', verbose_name='source')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datayear', verbose_name='millésime')),
            ],
            options={
                'verbose_name': 'données régions',
            },
        ),
    ]
