# Generated by Django 3.2.4 on 2021-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0014_datasource_regiondata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regiondata',
            constraint=models.UniqueConstraint(fields=('region', 'year', 'datacode'), name='unique metadata point'),
        ),
    ]
