# Generated by Django 3.2.4 on 2021-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0015_regiondata_unique metadata point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondata',
            name='datacode',
            field=models.CharField(max_length=255, verbose_name='code'),
        ),
    ]
