# Generated by Django 3.2.4 on 2021-06-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0018_auto_20210609_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpciData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datacode', models.CharField(max_length=255, verbose_name='code')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='valeur')),
                ('datatype', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
                ('epci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.epci', verbose_name='EPCI')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datasource', verbose_name='source')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datayear', verbose_name='millésime')),
            ],
            options={
                'verbose_name': 'donnée EPCI',
                'verbose_name_plural': 'données EPCI',
            },
        ),
        migrations.CreateModel(
            name='CommuneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datacode', models.CharField(max_length=255, verbose_name='code')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='valeur')),
                ('datatype', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.commune', verbose_name='commune')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datasource', verbose_name='source')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='francesubdivisions.datayear', verbose_name='millésime')),
            ],
            options={
                'verbose_name': 'donnée commune',
                'verbose_name_plural': 'données commune',
            },
        ),
        migrations.AddConstraint(
            model_name='epcidata',
            constraint=models.UniqueConstraint(fields=('epci', 'year', 'datacode'), name='unique epci data'),
        ),
        migrations.AddConstraint(
            model_name='communedata',
            constraint=models.UniqueConstraint(fields=('commune', 'year', 'datacode'), name='unique commune data'),
        ),
    ]
