# Generated by Django 3.2.4 on 2021-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0019_auto_20210609_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='category',
            field=models.CharField(blank=True, choices=[('REG', 'Région'), ('CTU', 'Collectivité territoriale unique')], max_length=3, null=True, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='region',
            name='siren',
            field=models.CharField(blank=True, max_length=9, verbose_name='numéro Siren'),
        ),
    ]
