# Generated by Django 3.2.4 on 2021-07-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0022_alter_datasource_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'insee')},
        ),
    ]
