# Generated by Django 3.2.4 on 2021-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0023_alter_region_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='category',
            field=models.CharField(blank=True, choices=[('DEPT', 'Département'), ('PARIS', 'Paris'), ('ML', 'Métropole de Lyon')], max_length=5, null=True, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='siren',
            field=models.CharField(blank=True, max_length=9, verbose_name='numéro Siren'),
        ),
    ]
