# Generated by Django 3.2.4 on 2021-07-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0024_auto_20210702_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.region', verbose_name='région'),
        ),
    ]
