# Generated by Django 3.2.4 on 2021-07-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0025_alter_departement_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='epci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.epci', verbose_name='EPCI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='siren',
            field=models.CharField(blank=True, max_length=9, verbose_name='numéro Siren'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='epci_type',
            field=models.CharField(blank=True, choices=[('CA', 'Communauté d’agglomération'), ('CC', 'Communauté de communes'), ('CU', 'Communauté urbaine'), ('MET69', 'Métropole de Lyon'), ('METRO', 'Métropole')], max_length=5, null=True, verbose_name='type d’EPCI'),
        ),
        migrations.AlterField(
            model_name='epci',
            name='siren',
            field=models.CharField(blank=True, max_length=9, verbose_name='numéro Siren'),
        ),
    ]
