# Generated by Django 3.2.4 on 2021-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0026_auto_20210702_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epci',
            name='siren',
            field=models.CharField(max_length=9, verbose_name='numéro Siren'),
        ),
    ]
