# Generated by Django 3.2.4 on 2021-07-05 10:06

from django.db import migrations, models
import francesubdivisions.services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0030_alter_departement_insee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='siren',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[francesubdivisions.services.validators.validate_siren], verbose_name='numéro Siren'),
        ),
    ]
