# Generated by Django 3.2.5 on 2021-07-22 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0032_alter_commune_insee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='insee',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^([0-1]\\d{4}|2[AB1-9]\\d{3}|[3-8]\\d{4}|9[0-5]\\d{3}|97[12346]\\d{2})$')], verbose_name='identifiant Insee'),
        ),
    ]
